// Route to Permission Mapping
// Maps route paths to required permissions from constants/permissions.js

export const ROUTE_PERMISSIONS = {
  // HR Module
  '/employees': 'HR_EMP_MASTER',
  '/employee-report': 'HR_EMP_MASTER',
  '/add-employee': 'HR_ADD_EMP',
  '/edit-employee': 'HR_ADD_EMP',
  '/photo': 'HR_PHOTO',
  '/profile-requests': 'HR_PROFILE_APPROVE',
  '/leave': 'HR_LEAVE_APP',
  '/leaves-master': 'HR_LEAVE_MASTER',
  '/onduty': 'HR_ONDUTY',
  '/onduty-preview': 'HR_ONDUTY_APPROVE',
  '/shiftchange': 'HR_SHIFT_CHG',
  '/attendance-mod': 'HR_ATT_MOD',
  '/hr-attendance': 'HR_ATT_ENTRY',
  '/tour': 'HR_TOUR',
  '/woffchange': 'HR_WOFF_CHG',
  '/advance': 'HR_ADVANCE',
  '/esileave': 'HR_ESI_LEAVE',
  '/tax': 'HR_PAYROLL_PROC',
  '/recruitment': 'HR_REPORTS',
  '/exit-settlement': 'HR_REPORTS',
  '/training': 'HR_REPORTS',
  '/pms': 'HR_REPORTS',
  '/disciplinary': 'HR_REPORTS',
  '/attendance-collector': 'HR_ATT_ENTRY',
  '/pf-accounting': 'HR_PAYROLL_PROC',
  '/payroll': 'HR_PAYROLL_PROC',
  '/holidays': 'HR_HOLIDAY_MASTER',
  '/shift-master': 'HR_SHIFT_MASTER',
  '/shiftschedule': 'HR_SHIFT_SCHED',
  '/muster-roll': 'HR_MUSTER',
  '/ot-approval': 'HR_OT_APP',
  '/my-attendance': 'HR_ATTENDANCE_REQUEST',
  '/attendance-requests': 'HR_ATTENDANCE_APPROVE',
  '/my-reports': 'HR_REPORTS_EMP',
  '/hr/reports': 'HR_REPORTS',
  '/hr/settings': 'HR_SETTINGS',
  '/hr': 'MOD_HR',
  '/employee-master': 'HR_EMP_MASTER',

  // ACCOUNTS Module
  '/accounts': 'MOD_ACCOUNTS',
  '/accounts/coa': 'ACC_DASHBOARD',
  '/accounts/budgets': 'ACC_SETTINGS',
  '/accounts/settings': 'ACC_SETTINGS',
  '/invoice/sales': 'ACC_INV_SALES',
  '/invoice/purchase': 'ACC_INV_PURCH',
  '/invoice/debit-note': 'ACC_INV_DEBIT',
  '/invoice/credit-note': 'ACC_INV_CREDIT',
  '/accounts/payment': 'ACC_VOUCH_PAY',
  '/accounts/receipt': 'ACC_VOUCH_REC',
  '/accounts/journal': 'ACC_VOUCH_JOUR',
  '/accounts/contra': 'ACC_VOUCH_CONTRA',
  '/accounts/voucher': 'ACC_VOUCH_JOUR',
  '/accounts/reports': 'ACC_REPORTS',
  '/reports/ledger': 'ACC_REPORTS',
  '/reports/daybook': 'ACC_REPORTS',
  '/reports/trial-balance': 'ACC_REPORTS',
  '/reports/pl': 'ACC_REPORTS',
  '/reports/balance-sheet': 'ACC_REPORTS',
  '/reports/ap': 'ACC_REPORTS',
  '/reports/ar': 'ACC_REPORTS',

  // PURCHASE Module
  '/purchase': 'MOD_PURCHASE',
  '/purchase/requisitions': 'PUR_REQ',
  '/purchase/requisitions/add': 'PUR_PR_NEW',
  '/purchase/requisitions/view': 'PUR_REQ',
  '/purchase/requisitions/edit': 'PUR_PR_NEW',
  '/purchase/requisitions/print': 'PUR_REQ',
  '/purchase/requisitions/sanction': 'PUR_PR_SANCTION',
  '/purchase/orders': 'PUR_ORDERS',
  '/purchase/orders/add': 'PUR_ORDERS',
  '/purchase/orders/view': 'PUR_ORDERS',
  '/purchase/orders/edit': 'PUR_ORDERS',
  '/purchase/rfq': 'PUR_RFQ',
  '/purchase/rfq/add': 'PUR_RFQ',
  '/purchase/rfq/view': 'PUR_RFQ',
  '/purchase/rfq/edit': 'PUR_RFQ',
  '/purchase/prices': 'PUR_PRICES',
  '/purchase/prices/add': 'PUR_PRICES',
  '/purchase/prices/view': 'PUR_PRICES',
  '/purchase/prices/edit': 'PUR_PRICES',
  '/purchase/rating': 'PUR_RATING',
  '/purchase/rating/add': 'PUR_RATING',
  '/purchase/vendors': 'PUR_VENDORS',
  '/purchase/vendors/add': 'PUR_VENDORS',
  '/purchase/vendors/view': 'PUR_VENDORS',
  '/purchase/vendors/edit': 'PUR_VENDORS',
  '/purchase/approvals': 'PUR_PR_AUTH',
  '/purchase/reports': 'PUR_REPORTS',
  '/purchase/daily-reports': 'PUR_REPORTS',
  '/purchase/job-orders': 'PUR_REPORTS',
  '/purchase/pr-amendment': 'PUR_PR_AUTH',
  '/purchase/settings': 'PUR_REPORTS',

  // STORES Module
  '/stores': 'MOD_STORES',
  '/stores/item-master': 'STORES_ITEM_MASTER',
  '/stores/item-master/add': 'STORES_ITEM_MASTER',
  '/stores/item-master/edit': 'STORES_ITEM_MASTER',
  '/stores/uom': 'STORES_ITEM_MASTER',
  '/stores/item-groups': 'STORES_ITEM_MASTER',
  '/stores/item-types': 'STORES_ITEM_MASTER',
  '/stores/grr': 'STORES_GRN',
  '/stores/grr/add': 'STORES_GRN',
  '/stores/grr/view': 'STORES_GRN',
  '/stores/grr/edit': 'STORES_GRN',
  '/stores/grr/print': 'STORES_GRN',
  '/stores/material-requisitions': 'STORES_ITEM_MASTER',
  '/stores/material-requisitions/add': 'STORES_ITEM_MASTER',
  '/stores/material-requisitions/view': 'STORES_ITEM_MASTER',
  '/stores/material-requisitions/edit': 'STORES_ITEM_MASTER',
  '/stores/material-requisitions/print': 'STORES_ITEM_MASTER',
  '/stores/material-issues': 'STORES_ISSUE',
  '/stores/material-issues/add': 'STORES_ISSUE',
  '/stores/material-issues/view': 'STORES_ISSUE',
  '/stores/material-issues/edit': 'STORES_ISSUE',
  '/stores/material-returns': 'STORES_RETURN',
  '/stores/material-returns/add': 'STORES_RETURN',
  '/stores/material-returns/view': 'STORES_RETURN',
  '/stores/material-returns/edit': 'STORES_RETURN',
  '/stores/delivery-challans': 'STORES_GATE',
  '/stores/delivery-challans/add': 'STORES_GATE',
  '/stores/delivery-challans/prepare': 'STORES_GATE',
  '/stores/delivery-challans/view': 'STORES_GATE',
  '/stores/delivery-challans/edit': 'STORES_GATE',
  '/stores/delivery-challans/repair': 'STORES_GATE',
  '/stores/delivery-challans/maintenance': 'STORES_GATE',
  '/stores/non-returnable-gate-passes': 'STORES_GATE',
  '/stores/non-returnable-gate-passes/new': 'STORES_GATE',
  '/stores/non-returnable-gate-passes/view': 'STORES_GATE',
  '/stores/non-returnable-gate-passes/edit': 'STORES_GATE',
  '/stores/inward-registers': 'STORES_GRN',
  '/stores/inward-registers/add': 'STORES_GRN',
  '/stores/inward-registers/edit': 'STORES_GRN',
  '/stores/inward-registers/view': 'STORES_GRN',
  '/stores/sale-approval': 'STORES_GATE',
  '/stores/invoices': 'STORES_GATE',
  '/stores/invoices/add': 'STORES_GATE',
  '/stores/invoices/view': 'STORES_GATE',
  '/stores/invoices/edit': 'STORES_GATE',
  '/stores/repair-billing': 'STORES_GATE',
  '/stores/maintenance-billing': 'STORES_GATE',
  '/stores/misc-voucher-billing': 'STORES_GATE',
  '/stores/cancellations': 'STORES_GATE',
  '/stores/approvals': 'STORES_GRN',
  '/inventory/ledger': 'STORES_STOCK_LEDGER',
  '/stores/stock-statement': 'STORES_STOCK_LEDGER',
  '/stores/warehouses': 'STORES_WAREHOUSE',
  '/stores/batches': 'STORES_BATCH',
  '/stores/day-wise-stock': 'STORES_STOCK_LEDGER',
  '/stores/stock-audit': 'STORES_PHYSICAL',
  '/stores/stock-audit/add': 'STORES_PHYSICAL',
  '/stores/stock-audit/view': 'STORES_PHYSICAL',
  '/stores/stock-audit/edit': 'STORES_PHYSICAL',
  '/stores/gate-entry': 'STORES_GATE',
  '/stores/gate-entry/add': 'STORES_GATE',
  '/stores/gate-entry/view': 'STORES_GATE',
  '/stores/gate-entry/edit': 'STORES_GATE',
  '/stores/reports': 'STORES_REPORTS',
  '/stores/settings': 'STORES_REPORTS',

  // PRODUCTION Module
  '/production': 'MOD_PRODUCTION',
  '/production/orders': 'PROD_ORDERS',
  '/production/machines': 'PROD_MACHINES',
  '/production/machines/add': 'PROD_MACHINES',
  '/production/machines/view': 'PROD_MACHINES',
  '/production/machines/edit': 'PROD_MACHINES',
  '/production/daily-entry': 'PROD_DAILY',
  '/production/daily-entry/add': 'PROD_DAILY',
  '/production/daily-entry/view': 'PROD_DAILY',
  '/production/daily-entry/edit': 'PROD_DAILY',
  '/production/downtime': 'PROD_DOWNTIME',
  '/production/downtime/add': 'PROD_DOWNTIME',
  '/production/downtime/view': 'PROD_DOWNTIME',
  '/production/downtime/edit': 'PROD_DOWNTIME',
  '/production/reports': 'PROD_REPORTS',
  '/production/settings': 'PROD_SETTINGS',

  // PLANNING Module
  '/planning': 'MOD_PLANNING',
  '/planning/schedule': 'PLAN_SCHEDULE',
  '/planning/schedule/add': 'PLAN_SCHEDULE',
  '/planning/schedule/view': 'PLAN_SCHEDULE',
  '/planning/schedule/edit': 'PLAN_SCHEDULE',
  '/planning/mrp': 'PLAN_MRP',
  '/planning/mrp/add': 'PLAN_MRP',
  '/planning/mrp/view': 'PLAN_MRP',
  '/planning/mrp/edit': 'PLAN_MRP',
  '/planning/capacity': 'PLAN_CAPACITY',
  '/planning/capacity/add': 'PLAN_CAPACITY',
  '/planning/capacity/view': 'PLAN_CAPACITY',
  '/planning/capacity/edit': 'PLAN_CAPACITY',
  '/planning/reports': 'PLAN_REPORTS',
  '/planning/settings': 'PLAN_SETTINGS',

  // ENGINEERING Module
  '/engineering': 'MOD_ENGINEERING',
  '/engineering/categories': 'ENG_ITEMS',
  '/engineering/products': 'ENG_ITEMS',
  '/engineering/products/add': 'ENG_ITEMS',
  '/engineering/products/view': 'ENG_ITEMS',
  '/engineering/products/edit': 'ENG_ITEMS',
  '/engineering/bom': 'ENG_BOM',
  '/engineering/bom/add': 'ENG_BOM',
  '/engineering/bom/view': 'ENG_BOM',
  '/engineering/bom/edit': 'ENG_BOM',
  '/engineering/reports': 'ENG_REPORTS',
  '/engineering/settings': 'ENG_REPORTS',

  // MARKETING Module
  '/marketing': 'MOD_MARKETING',
  '/marketing/customers': 'MARK_CUSTOMERS',
  '/marketing/customers/add': 'MARK_CUSTOMERS',
  '/marketing/customers/view': 'MARK_CUSTOMERS',
  '/marketing/customers/edit': 'MARK_CUSTOMERS',
  '/marketing/leads': 'MARK_LEADS',
  '/marketing/leads/add': 'MARK_LEADS',
  '/marketing/leads/view': 'MARK_LEADS',
  '/marketing/leads/edit': 'MARK_LEADS',
  '/marketing/quotes': 'MARK_QUOTES',
  '/marketing/quotes/add': 'MARK_QUOTES',
  '/marketing/quotes/view': 'MARK_QUOTES',
  '/marketing/quotes/edit': 'MARK_QUOTES',
  '/marketing/orders': 'MARK_ORDERS',
  '/marketing/orders/add': 'MARK_ORDERS',
  '/marketing/orders/view': 'MARK_ORDERS',
  '/marketing/orders/edit': 'MARK_ORDERS',
  '/marketing/reports': 'MARK_REPORTS',
  '/marketing/settings': 'MARK_SETTINGS',

  // QUALITY Module
  '/quality': 'MOD_QUALITY',
  '/quality/incoming': 'QUAL_INCOMING',
  '/quality/process': 'QUAL_PROCESS',
  '/quality/final': 'QUAL_FINAL',
  '/quality/inspections': 'QUAL_INCOMING',
  '/quality/inspections/add': 'QUAL_INCOMING',
  '/quality/inspections/view': 'QUAL_INCOMING',
  '/quality/inspections/edit': 'QUAL_INCOMING',
  '/quality/non-conformances': 'QUAL_INCOMING',
  '/quality/non-conformances/add': 'QUAL_INCOMING',
  '/quality/non-conformances/view': 'QUAL_INCOMING',
  '/quality/non-conformances/edit': 'QUAL_INCOMING',
  '/quality/reports': 'QUAL_REPORTS',
  '/quality/settings': 'QUAL_SETTINGS',

  // MAINTENANCE Module
  '/maintenance': 'MOD_MAINTENANCE',
  '/maintenance/machines': 'MAINT_MACHINES',
  '/maintenance/machines/add': 'MAINT_MACHINES',
  '/maintenance/machines/view': 'MAINT_MACHINES',
  '/maintenance/machines/edit': 'MAINT_MACHINES',
  '/maintenance/assets': 'MAINT_ASSETS',
  '/maintenance/assets/add': 'MAINT_ASSETS',
  '/maintenance/assets/view': 'MAINT_ASSETS',
  '/maintenance/assets/edit': 'MAINT_ASSETS',
  '/maintenance/schedule': 'MAINT_SCHEDULE',
  '/maintenance/schedule/add': 'MAINT_SCHEDULE',
  '/maintenance/schedule/view': 'MAINT_SCHEDULE',
  '/maintenance/schedule/edit': 'MAINT_SCHEDULE',
  '/maintenance/reports': 'MAINT_REPORTS',
  '/maintenance/settings': 'MAINT_SETTINGS',

  // SUBCONTRACT Module
  '/subcontract': 'MOD_SUBCONTRACT',
  '/subcontract/orders': 'SUB_ORDERS',
  '/subcontract/orders/add': 'SUB_ORDERS',
  '/subcontract/orders/view': 'SUB_ORDERS',
  '/subcontract/orders/edit': 'SUB_ORDERS',
  '/subcontract/issue': 'SUB_ISSUE',
  '/subcontract/issue/add': 'SUB_ISSUE',
  '/subcontract/issue/view': 'SUB_ISSUE',
  '/subcontract/issue/edit': 'SUB_ISSUE',
  '/subcontract/receipt': 'SUB_RECEIPT',
  '/subcontract/receipt/add': 'SUB_RECEIPT',
  '/subcontract/receipt/view': 'SUB_RECEIPT',
  '/subcontract/receipt/edit': 'SUB_RECEIPT',
  '/subcontract/reports': 'SUB_REPORTS',
  '/subcontract/settings': 'SUB_SETTINGS',
};

// Helper to get permission for a route (handles dynamic routes)
export const getRoutePermission = (pathname) => {
  // Exact match first
  if (ROUTE_PERMISSIONS[pathname]) {
    return ROUTE_PERMISSIONS[pathname];
  }
  // Check parent paths (e.g., /edit-employee/123 -> /edit-employee)
  const parts = pathname.split('/').filter(Boolean);
  for (let i = parts.length; i > 0; i--) {
    const parentPath = '/' + parts.slice(0, i).join('/');
    if (ROUTE_PERMISSIONS[parentPath]) {
      return ROUTE_PERMISSIONS[parentPath];
    }
  }
  return null; // No permission required (public or handled by module access)
};