const bcrypt = require('bcryptjs');
const db = require('./models');
require('dotenv').config();

// Full permission catalog (mirrors frontend/src/constants/permissions.js).
// ADMIN users receive all of these; scoped employees receive a subset.
const ALL_PERMISSIONS = [
  'MOD_HR', 'HR_DASHBOARD', 'HR_EMP_MASTER', 'HR_ADD_EMP', 'HR_PHOTO', 'HR_PROFILE_APPROVE',
  'HR_SHIFT_MASTER', 'HR_HOLIDAY_MASTER', 'HR_LEAVE_MASTER', 'HR_ATT_ENTRY', 'HR_ATT_MOD',
  'HR_SHIFT_SCHED', 'HR_MUSTER', 'HR_OT_APP', 'HR_ADVANCE', 'HR_PAYROLL_PROC', 'HR_ESI_LEAVE',
  'HR_LEAVE_APP', 'HR_LEAVE_APPROVE', 'HR_ONDUTY', 'HR_ONDUTY_APPROVE', 'HR_TOUR', 'HR_TOUR_APPROVE',
  'HR_SHIFT_CHG', 'HR_SHIFT_CHG_APPROVE', 'HR_WOFF_CHG', 'HR_REPORTS', 'HR_SETTINGS',
  'MOD_ACCOUNTS', 'ACC_DASHBOARD', 'ACC_INV_SALES', 'ACC_INV_PURCH', 'ACC_INV_DEBIT', 'ACC_INV_CREDIT',
  'ACC_VOUCH_PAY', 'ACC_VOUCH_REC', 'ACC_VOUCH_JOUR', 'ACC_VOUCH_CONTRA', 'ACC_REPORTS', 'ACC_SETTINGS',
  'MOD_STORES', 'STORES_DASHBOARD', 'STORES_ITEM_MASTER', 'STORES_STOCK_LEDGER', 'STORES_PHYSICAL',
  'STORES_GATE', 'STORES_GRN', 'STORES_ISSUE', 'STORES_RETURN', 'STORES_REPORTS',
  'MOD_PURCHASE', 'PUR_DASHBOARD', 'PUR_REQ', 'PUR_PR_NEW', 'PUR_PR_AUTH', 'PUR_PR_SANCTION',
  'PUR_PR_STATUS', 'PUR_LOI', 'PUR_PR_SHORTCLOSE', 'PUR_RFQ', 'PUR_ORDERS', 'PUR_VENDORS',
  'PUR_PRICES', 'PUR_RATING', 'PUR_REPORTS',
  'MOD_PRODUCTION', 'PROD_DASHBOARD', 'PROD_ORDERS', 'PROD_DAILY', 'PROD_MACHINES', 'PROD_DOWNTIME', 'PROD_REPORTS', 'PROD_SETTINGS',
  'MOD_PLANNING', 'PLAN_DASHBOARD', 'PLAN_SCHEDULE', 'PLAN_MRP', 'PLAN_CAPACITY', 'PLAN_REPORTS', 'PLAN_SETTINGS',
  'MOD_ENGINEERING', 'ENG_DASHBOARD', 'ENG_ITEMS', 'ENG_BOM', 'ENG_BOM_DIFF', 'ENG_ROUTING', 'ENG_WORK_CENTERS', 'ENG_REPORTS',
  'MOD_MARKETING', 'MARK_DASHBOARD', 'MARK_LEADS', 'MARK_QUOTES', 'MARK_ORDERS', 'MARK_CUSTOMERS', 'MARK_REPORTS', 'MARK_SETTINGS',
  'MOD_QUALITY', 'QUAL_DASHBOARD', 'QUAL_INCOMING', 'QUAL_PROCESS', 'QUAL_FINAL', 'QUAL_REPORTS', 'QUAL_SETTINGS',
  'MOD_MAINTENANCE', 'MAINT_DASHBOARD', 'MAINT_MACHINES', 'MAINT_ASSETS', 'MAINT_SCHEDULE', 'MAINT_REPORTS', 'MAINT_SETTINGS',
  'MOD_SUBCONTRACT', 'SUB_DASHBOARD', 'SUB_ORDERS', 'SUB_ISSUE', 'SUB_RECEIPT', 'SUB_REPORTS', 'SUB_SETTINGS',
];

// A realistic "Stores + Subcontract clerk" scope to demo employee-wise access.
const STORES_CLERK_PERMISSIONS = [
  'MOD_STORES', 'STORES_DASHBOARD', 'STORES_ITEM_MASTER', 'STORES_STOCK_LEDGER',
  'STORES_GATE', 'STORES_GRN', 'STORES_ISSUE', 'STORES_RETURN', 'STORES_REPORTS',
  'MOD_SUBCONTRACT', 'SUB_DASHBOARD', 'SUB_ORDERS', 'SUB_ISSUE', 'SUB_RECEIPT', 'SUB_REPORTS',
];

const employeesData = [
    // 🔹 Active Employees
    {
        empid: 1002,
        company_id: 1,
        unit_id: 1,
        div_id: 1,
        dept_id: 1,
        sec_id: 1,
        designation_id: 1,
        divname: 'Maintenance',
        deptname: 'Maintenance',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'TANGELLA SRINIVAS',
        fname: 'Venkat Rao',
        dob: new Date('1981-04-27'),
        pob: 'Hyderabad',
        bgroup: 'O+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, Hindi, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9490499414',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1003,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'CHAKALI ANJANEYULU',
        fname: 'Yadaiah',
        dob: new Date('1992-01-01'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9704959355',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1005,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'NAMBARI SRINIVASA RAO',
        fname: 'Chinna Rao',
        dob: new Date('1977-08-06'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9666205452',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1006,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'J RAVI',
        fname: 'Laxmi Narayana',
        dob: new Date('1985-01-26'),
        pob: 'Hyderabad',
        bgroup: 'O+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9848574304',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1009,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 1,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'F',
        marital_status: 'Married',
        ename: 'RAMAVATH JYOTHI',
        fname: 'Ramavath Bodaiah',
        dob: new Date('1986-05-05'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '8341923565',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1010,
        company_id: 1,
        unit_id: 1,
        div_id: 3,
        dept_id: 3,
        sec_id: 1,
        designation_id: 1,
        divname: 'Quality',
        deptname: 'Quality',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'BURUGUPALLI MANI KANTA',
        fname: 'Burugupalli Basava Raju',
        dob: new Date('2002-07-18'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '7989978892',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1016,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 1,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'S. NARESH',
        fname: 'Chander Naik',
        dob: new Date('2004-07-16'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '8591032205',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1019,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'F',
        marital_status: 'Married',
        ename: 'PATLURI SOWJANYA',
        fname: 'Sidhu',
        dob: new Date('1996-03-26'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9154242796',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1021,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'BERI SIVA',
        fname: 'Ravi',
        dob: new Date('2003-02-21'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '8143121124',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1022,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'JANGAM GOPI',
        fname: 'Nancharaiah',
        dob: new Date('1973-02-01'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9390636860',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1024,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'TUMMA VISHNU PRASAD',
        fname: 'Nancharaiah',
        dob: new Date('2003-05-06'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9381912553',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1025,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'KONDALA APPALASURI',
        fname: '',
        dob: new Date('1994-05-21'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9398080073',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1026,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 1,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'BADAROTH VENKATESH',
        fname: 'Balaram',
        dob: new Date('2002-10-25'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '7794813894',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1027,
        company_id: 1,
        unit_id: 1,
        div_id: 3,
        dept_id: 3,
        sec_id: 1,
        designation_id: 2,
        divname: 'Quality',
        deptname: 'Quality',
        secname: 'Section 1',
        gender: 'F',
        marital_status: 'Single',
        ename: 'ANNAVARAPU RAMYA',
        fname: '',
        dob: new Date('1991-06-20'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '6300530652',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },

    // 🔹 Left Employees
    {
        empid: 1013,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 3,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'NAMANA SUJIT KUMAR',
        fname: 'Namana Venkateswar Rao',
        dob: new Date('1994-07-27'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: false,
        created_by: '1001'
    },
    {
        empid: 1004,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'DASHARATHA YASHWANTH',
        fname: 'Gopi Kishan Raju',
        dob: new Date('2000-07-07'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9100145586',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: false,
        created_by: '1001'
    },
    // 🔹 Add remaining left employees similarly (1015, 1018, 1017, 1020, 1008, 1012, 1023)
];

const seedAll = async () => {
    console.log('🌱 Starting Data Seeding...');

    try {
        await db.sequelize.authenticate();
        console.log('✅ Connected to database.');

        await db.sequelize.sync({ alter: true });

        for (const emp of employeesData) {
            const employee = await db.EmployeeMaster.create(emp);

            // Create User
            const salt = await bcrypt.genSalt(10);
            const hashedPassword = await bcrypt.hash('AUCTOR', salt);

            await db.User.create({
                username: String(emp.empid),
                password_hash: hashedPassword,
                empid: emp.empid,
                ename: emp.ename,
                role: 'ADMIN',
                permissions: ALL_PERMISSIONS,
                is_active: emp.is_active,
                created_by: '1001'
            });

            // Official record
            await db.EmpOfficial.create({
                empid: emp.empid,
                doj: emp.dob,
                emp_status: emp.is_active ? 'A' : 'L',
                bankacno: '0000000000',
                pfacno: '',
                esiacno: '',
                bankname: 'HDFC',
                ifsccode: 'HDFC0000081'
            });

            // Salary record
            await db.EmpSalary.create({
                empid: emp.empid,
                basic: 10000,
                hra: 5000,
                total: 15000,
                created_by: '1001'
            });

            // Leave master
            await db.LeaveMaster.create({
                empid: emp.empid,
                unit: 'UNIT1',
                cls_eligible: 12,
                cls_utilised: 0,
                cls_balance: 12,
                els_eligible: 15,
                els_utilised: 0,
                els_balance: 15,
                cls_last_update: new Date(),
                els_last_update: new Date(),
                final_status: 1
            });

            console.log(`✅ Created: ${emp.empid} - ${emp.ename}`);
        }

        console.log('✅ Seeding Complete!');

        // ── Demo scoped employee (shows employee-wise permission limits) ──
        const demoEmpId = 2001;
        const existing = await db.EmployeeMaster.findOne({ where: { empid: demoEmpId } });
        if (!existing) {
            await db.EmployeeMaster.create({
                empid: demoEmpId, company_id: 1, unit_id: 1, div_id: 4, dept_id: 4, sec_id: 1,
                designation_id: 1, divname: 'Stores', deptname: 'Stores', secname: 'Section 1',
                gender: 'M', marital_status: 'Married', ename: 'DEMO STORES CLERK', fname: 'Clerk',
                dob: new Date('1995-01-01'), bgroup: 'O+', mother_tongue: 'Telugu',
                lang_known: 'Telugu, English', cadd_city: 'Hyderabad', cadd_state: 'Telangana',
                is_active: true, created_by: '1001',
            });
            await db.EmpOfficial.create({ empid: demoEmpId, doj: new Date('2020-01-01'), emp_status: 'A', bankacno: '0000000000', bankname: 'HDFC', ifsccode: 'HDFC0000081' });
            await db.EmpSalary.create({ empid: demoEmpId, basic: 18000, hra: 6000, total: 24000, created_by: '1001' });
        }
        const salt2 = await bcrypt.genSalt(10);
        const hash2 = await bcrypt.hash('AUCTOR', salt2);
        await db.User.findOrCreate({
            where: { username: 'EMP001' },
            defaults: {
                username: 'EMP001', password_hash: hash2, empid: demoEmpId,
                ename: 'DEMO STORES CLERK', role: 'USER', permissions: STORES_CLERK_PERMISSIONS,
                is_active: true, created_by: '1001',
            },
        });
        console.log('✅ Demo employee (EMP001 / AUCTOR) seeded with Stores+Subcontract scope.');

        process.exit(0);
    } catch (error) {
        console.error('❌ Seeding Error:', error);
        process.exit(1);
    }
};

seedAll();
