const bcrypt = require('bcryptjs');
const db = require('./models');
require('dotenv').config();

const employeesData = [
    // 🔹 Active Employees
    {
        empid: 1002,
        company_id: 1,
        unit_id: 1,
        div_id: 1,
        dept_id: 1,
        sec_id: 1,
        designation_id: 1,
        divname: 'Maintenance',
        deptname: 'Maintenance',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'TANGELLA SRINIVAS',
        fname: 'Venkat Rao',
        dob: new Date('1981-04-27'),
        pob: 'Hyderabad',
        bgroup: 'O+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, Hindi, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9490499414',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1003,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'CHAKALI ANJANEYULU',
        fname: 'Yadaiah',
        dob: new Date('1992-01-01'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9704959355',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1005,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'NAMBARI SRINIVASA RAO',
        fname: 'Chinna Rao',
        dob: new Date('1977-08-06'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9666205452',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1006,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'J RAVI',
        fname: 'Laxmi Narayana',
        dob: new Date('1985-01-26'),
        pob: 'Hyderabad',
        bgroup: 'O+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9848574304',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1009,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 1,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'F',
        marital_status: 'Married',
        ename: 'RAMAVATH JYOTHI',
        fname: 'Ramavath Bodaiah',
        dob: new Date('1986-05-05'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '8341923565',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1010,
        company_id: 1,
        unit_id: 1,
        div_id: 3,
        dept_id: 3,
        sec_id: 1,
        designation_id: 1,
        divname: 'Quality',
        deptname: 'Quality',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'BURUGUPALLI MANI KANTA',
        fname: 'Burugupalli Basava Raju',
        dob: new Date('2002-07-18'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '7989978892',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1016,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 1,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'S. NARESH',
        fname: 'Chander Naik',
        dob: new Date('2004-07-16'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '8591032205',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1019,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'F',
        marital_status: 'Married',
        ename: 'PATLURI SOWJANYA',
        fname: 'Sidhu',
        dob: new Date('1996-03-26'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9154242796',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1021,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'BERI SIVA',
        fname: 'Ravi',
        dob: new Date('2003-02-21'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '8143121124',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1022,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'JANGAM GOPI',
        fname: 'Nancharaiah',
        dob: new Date('1973-02-01'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9390636860',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1024,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'TUMMA VISHNU PRASAD',
        fname: 'Nancharaiah',
        dob: new Date('2003-05-06'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9381912553',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1025,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 2,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Married',
        ename: 'KONDALA APPALASURI',
        fname: '',
        dob: new Date('1994-05-21'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9398080073',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1026,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 1,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'BADAROTH VENKATESH',
        fname: 'Balaram',
        dob: new Date('2002-10-25'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '7794813894',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },
    {
        empid: 1027,
        company_id: 1,
        unit_id: 1,
        div_id: 3,
        dept_id: 3,
        sec_id: 1,
        designation_id: 2,
        divname: 'Quality',
        deptname: 'Quality',
        secname: 'Section 1',
        gender: 'F',
        marital_status: 'Single',
        ename: 'ANNAVARAPU RAMYA',
        fname: '',
        dob: new Date('1991-06-20'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '6300530652',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: true,
        created_by: '1001'
    },

    // 🔹 Left Employees
    {
        empid: 1013,
        company_id: 1,
        unit_id: 1,
        div_id: 2,
        dept_id: 2,
        sec_id: 1,
        designation_id: 3,
        divname: 'Production',
        deptname: 'Production',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'NAMANA SUJIT KUMAR',
        fname: 'Namana Venkateswar Rao',
        dob: new Date('1994-07-27'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: false,
        created_by: '1001'
    },
    {
        empid: 1004,
        company_id: 1,
        unit_id: 1,
        div_id: 4,
        dept_id: 4,
        sec_id: 1,
        designation_id: 1,
        divname: 'Stores',
        deptname: 'Stores',
        secname: 'Section 1',
        gender: 'M',
        marital_status: 'Single',
        ename: 'DASHARATHA YASHWANTH',
        fname: 'Gopi Kishan Raju',
        dob: new Date('2000-07-07'),
        pob: 'Hyderabad',
        bgroup: 'B+',
        mother_tongue: 'Telugu',
        lang_known: 'Telugu, English',
        cadd_city: 'Hyderabad',
        cadd_state: 'Telangana',
        cadd_mobile: '9100145586',
        padd_city: 'Hyderabad',
        padd_state: 'Telangana',
        is_active: false,
        created_by: '1001'
    },
    // 🔹 Add remaining left employees similarly (1015, 1018, 1017, 1020, 1008, 1012, 1023)
];

const seedAll = async () => {
    console.log('🌱 Starting Data Seeding...');

    try {
        await db.sequelize.authenticate();
        console.log('✅ Connected to database.');

        await db.sequelize.sync({ alter: true });

        for (const emp of employeesData) {
            const employee = await db.EmployeeMaster.create(emp);

            // Create User
            const salt = await bcrypt.genSalt(10);
            const hashedPassword = await bcrypt.hash('AUCTOR', salt);

            await db.User.create({
                username: String(emp.empid),
                password_hash: hashedPassword,
                empid: emp.empid,
                ename: emp.ename,
                role: 'ADMIN',
                is_active: emp.is_active,
                created_by: '1001'
            });

            // Official record
            await db.EmpOfficial.create({
                empid: emp.empid,
                doj: emp.dob,
                emp_status: emp.is_active ? 'A' : 'L',
                bankacno: '0000000000',
                pfacno: '',
                esiacno: '',
                bankname: 'HDFC',
                ifsccode: 'HDFC0000081'
            });

            // Salary record
            await db.EmpSalary.create({
                empid: emp.empid,
                basic: 10000,
                hra: 5000,
                total: 15000,
                created_by: '1001'
            });

            // Leave master
            await db.LeaveMaster.create({
                empid: emp.empid,
                unit: 'UNIT1',
                cls_eligible: 12,
                cls_utilised: 0,
                cls_balance: 12,
                els_eligible: 15,
                els_utilised: 0,
                els_balance: 15,
                cls_last_update: new Date(),
                els_last_update: new Date(),
                final_status: 1
            });

            console.log(`✅ Created: ${emp.empid} - ${emp.ename}`);
        }

        console.log('✅ Seeding Complete!');
        process.exit(0);
    } catch (error) {
        console.error('❌ Seeding Error:', error);
        process.exit(1);
    }
};

seedAll();
