BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE hr.legacy_hr_employees';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE erp.legacy_erp_items';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
EXIT;
