const { DataTypes } = require('sequelize');

module.exports = (sequelize) => ({
  ExitApplication: sequelize.define('ExitApplication', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    empid: { type: DataTypes.INTEGER, allowNull: false },
    empname: { type: DataTypes.STRING(200) },
    resignation_date: { type: DataTypes.DATEONLY },
    last_working_day: { type: DataTypes.DATEONLY },
    reason: { type: DataTypes.TEXT },
    type: { type: DataTypes.STRING(30), defaultValue: 'Resignation' },
    status: { type: DataTypes.STRING(20), defaultValue: 'Submitted' },
    approved_by: { type: DataTypes.STRING(100) },
    approved_date: { type: DataTypes.DATEONLY },
    remarks: { type: DataTypes.TEXT },
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName: 't_exit_application', timestamps: false, underscored: true }),

  ExitClearance: sequelize.define('ExitClearance', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    exit_application_id: { type: DataTypes.INTEGER, allowNull: false },
    department: { type: DataTypes.STRING(100), allowNull: false },
    cleared_by: { type: DataTypes.STRING(100) },
    cleared_date: { type: DataTypes.DATEONLY },
    status: { type: DataTypes.STRING(20), defaultValue: 'Pending' },
    remarks: { type: DataTypes.TEXT },
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName: 't_exit_clearance', timestamps: false, underscored: true }),

  FinalSettlement: sequelize.define('FinalSettlement', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    exit_application_id: { type: DataTypes.INTEGER, allowNull: false },
    empid: { type: DataTypes.INTEGER },
    full_name: { type: DataTypes.STRING(200) },
    designation: { type: DataTypes.STRING(200) },
    department: { type: DataTypes.STRING(100) },
    date_of_joining: { type: DataTypes.DATEONLY },
    last_working_day: { type: DataTypes.DATEONLY },
    total_tenure_years: { type: DataTypes.DECIMAL(5, 2) },
    notice_period_days: { type: DataTypes.INTEGER, defaultValue: 0 },
    notice_period_amount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    notice_recovered: { type: DataTypes.BOOLEAN, defaultValue: false },
    leave_balance_days: { type: DataTypes.DECIMAL(5, 1), defaultValue: 0 },
    leave_encashment_amount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    gratuity_eligible: { type: DataTypes.BOOLEAN, defaultValue: false },
    gratuity_amount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    salary_due_days: { type: DataTypes.INTEGER, defaultValue: 0 },
    salary_due_amount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    other_earnings: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    other_deductions: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    other_deductions_remarks: { type: DataTypes.TEXT },
    gross_payable: { type: DataTypes.DECIMAL(14, 2), defaultValue: 0 },
    tds_deducted: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
    net_payable: { type: DataTypes.DECIMAL(14, 2), defaultValue: 0 },
    settlement_date: { type: DataTypes.DATEONLY },
    status: { type: DataTypes.STRING(20), defaultValue: 'Draft' },
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName: 't_final_settlement', timestamps: false, underscored: true }),
});
