const { DataTypes } = require('sequelize');

module.exports = (sequelize) => ({
  JobRequisition: sequelize.define('JobRequisition', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    req_no: { type: DataTypes.STRING(30), allowNull: false, unique: true },
    position_title: { type: DataTypes.STRING(200), allowNull: false },
    department: { type: DataTypes.STRING(100) },
    no_of_positions: { type: DataTypes.INTEGER, defaultValue: 1 },
    qualification: { type: DataTypes.TEXT },
    experience_years: { type: DataTypes.INTEGER },
    location: { type: DataTypes.STRING(200) },
    salary_range: { type: DataTypes.STRING(100) },
    description: { type: DataTypes.TEXT },
    status: { type: DataTypes.STRING(20), defaultValue: 'Draft' },
    requested_by: { type: DataTypes.STRING(100) },
    approved_by: { type: DataTypes.STRING(100) },
    approved_date: { type: DataTypes.DATEONLY },
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName: 't_job_requisition', timestamps: false, underscored: true }),

  Candidate: sequelize.define('Candidate', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    requisition_id: { type: DataTypes.INTEGER },
    name: { type: DataTypes.STRING(200), allowNull: false },
    email: { type: DataTypes.STRING(200) },
    phone: { type: DataTypes.STRING(20) },
    resume_url: { type: DataTypes.TEXT },
    current_company: { type: DataTypes.STRING(200) },
    experience_years: { type: DataTypes.DECIMAL(4, 1) },
    qualification: { type: DataTypes.STRING(200) },
    source: { type: DataTypes.STRING(50), defaultValue: 'Portal' },
    status: { type: DataTypes.STRING(20), defaultValue: 'New' },
    applied_date: { type: DataTypes.DATEONLY },
    remarks: { type: DataTypes.TEXT },
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName: 't_candidate', timestamps: false, underscored: true }),

  Interview: sequelize.define('Interview', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    candidate_id: { type: DataTypes.INTEGER, allowNull: false },
    requisition_id: { type: DataTypes.INTEGER },
    round: { type: DataTypes.INTEGER, defaultValue: 1 },
    interview_date: { type: DataTypes.DATE },
    interviewer: { type: DataTypes.STRING(200) },
    mode: { type: DataTypes.STRING(50), defaultValue: 'In-person' },
    status: { type: DataTypes.STRING(20), defaultValue: 'Scheduled' },
    feedback: { type: DataTypes.TEXT },
    rating: { type: DataTypes.INTEGER },
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName: 't_interview', timestamps: false, underscored: true }),

  OfferLetter: sequelize.define('OfferLetter', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    candidate_id: { type: DataTypes.INTEGER, allowNull: false },
    offer_no: { type: DataTypes.STRING(30), allowNull: false, unique: true },
    position_title: { type: DataTypes.STRING(200) },
    department: { type: DataTypes.STRING(100) },
    ctc: { type: DataTypes.DECIMAL(14, 2) },
    joining_date: { type: DataTypes.DATEONLY },
    status: { type: DataTypes.STRING(20), defaultValue: 'Draft' },
    issued_date: { type: DataTypes.DATEONLY },
    accepted_date: { type: DataTypes.DATEONLY },
    remarks: { type: DataTypes.TEXT },
    created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  }, { tableName: 't_offer_letter', timestamps: false, underscored: true }),
});
