export const PERMISSIONS = {
  HR: [
    { id: 'MOD_HR', label: 'Access HR Module' },
    { id: 'HR_DASHBOARD', label: 'Dashboard' },
    { id: 'HR_EMP_MASTER', label: 'Employee Master' },
    { id: 'HR_ADD_EMP', label: 'Add New Employee' },
    { id: 'HR_PHOTO', label: 'Photo Upload' },
    { id: 'HR_PROFILE_APPROVE', label: 'Profile Update Requests' },
    { id: 'HR_SHIFT_MASTER', label: 'Shift Master' },
    { id: 'HR_HOLIDAY_MASTER', label: 'Holiday Master' },
    { id: 'HR_LEAVE_MASTER', label: 'Leaves Master' },
    { id: 'HR_ATT_ENTRY', label: 'Attendance Entry' },
    { id: 'HR_ATT_MOD', label: 'Attendance Correction' },
    { id: 'HR_SHIFT_SCHED', label: 'Shift Schedule' },
    { id: 'HR_MUSTER', label: 'Muster Roll' },
    { id: 'HR_OT_APP', label: 'OT Approval' },
    { id: 'HR_ADVANCE', label: 'Salary Advances' },
    { id: 'HR_PAYROLL_PROC', label: 'Monthly Payroll' },
    { id: 'HR_ESI_LEAVE', label: 'ESI Leaves' },
    { id: 'HR_LEAVE_APP', label: 'Leave Applications (Apply/View)' },
    { id: 'HR_LEAVE_APPROVE', label: 'Leave Applications (Approve/Reject)' },
    { id: 'HR_ONDUTY', label: 'On-Duty Requests (Apply/View)' },
    { id: 'HR_ONDUTY_APPROVE', label: 'On-Duty Requests (Approve/Reject)' },
    { id: 'HR_TOUR', label: 'Tour Applications (Apply/View)' },
    { id: 'HR_TOUR_APPROVE', label: 'Tour Applications (Approve/Reject)' },
    { id: 'HR_SHIFT_CHG', label: 'Shift Change (Request)' },
    { id: 'HR_SHIFT_CHG_APPROVE', label: 'Shift Change (Approve)' },
    { id: 'HR_WOFF_CHG', label: 'Weekly Off Change' },
    { id: 'HR_REPORTS', label: 'Reports' },
    { id: 'HR_SETTINGS', label: 'Settings' },
  ],
  ACCOUNTS: [
    { id: 'MOD_ACCOUNTS', label: 'Access ACCOUNTS Module' },
    { id: 'ACC_DASHBOARD', label: 'Dashboard' },
    { id: 'ACC_INV_SALES', label: 'Sales Invoice' },
    { id: 'ACC_INV_PURCH', label: 'Purchase Invoice' },
    { id: 'ACC_INV_DEBIT', label: 'Debit Note' },
    { id: 'ACC_INV_CREDIT', label: 'Credit Note' },
    { id: 'ACC_VOUCH_PAY', label: 'Payment Voucher' },
    { id: 'ACC_VOUCH_REC', label: 'Receipt Voucher' },
    { id: 'ACC_VOUCH_JOUR', label: 'Journal Voucher' },
    { id: 'ACC_VOUCH_CONTRA', label: 'Contra Entry' },
    { id: 'ACC_REPORTS', label: 'Reports' },
    { id: 'ACC_SETTINGS', label: 'Settings' },
  ],
  STORES: [
    { id: 'MOD_STORES', label: 'Access STORES Module' },
    { id: 'STORES_DASHBOARD', label: 'Dashboard' },
    { id: 'STORES_ITEM_MASTER', label: 'Item Master' },
    { id: 'STORES_STOCK_LEDGER', label: 'Stock Ledger' },
    { id: 'STORES_PHYSICAL', label: 'Physical Verification' },
    { id: 'STORES_GATE', label: 'Gate Entry' },
    { id: 'STORES_GRN', label: 'GRN / MRN' },
    { id: 'STORES_ISSUE', label: 'Material Issue' },
    { id: 'STORES_RETURN', label: 'Material Return' },
    { id: 'STORES_REPORTS', label: 'Reports' },
  ],
  PURCHASE: [
    { id: 'MOD_PURCHASE', label: 'Access PURCHASE Module' },
    { id: 'PUR_DASHBOARD', label: 'Dashboard' },
    { id: 'PUR_REQ', label: 'Purchase Requisitions' },
    { id: 'PUR_PR_NEW', label: 'PR - New' },
    { id: 'PUR_PR_AUTH', label: 'PR - Authorization' },
    { id: 'PUR_PR_SANCTION', label: 'PR - Sanction' },
    { id: 'PUR_PR_STATUS', label: 'PR - Status Updation' },
    { id: 'PUR_LOI', label: 'Letter of Indent' },
    { id: 'PUR_PR_SHORTCLOSE', label: 'PR - Short Close' },
    { id: 'PUR_RFQ', label: 'Enquiry / RFQ' },
    { id: 'PUR_ORDERS', label: 'Purchase Orders' },
    { id: 'PUR_VENDORS', label: 'Vendor Master' },
    { id: 'PUR_PRICES', label: 'Price List Master' },
    { id: 'PUR_RATING', label: 'Vendor Rating' },
    { id: 'PUR_REPORTS', label: 'Reports' },
  ],
  PRODUCTION: [
    { id: 'MOD_PRODUCTION', label: 'Access PRODUCTION Module' },
    { id: 'PROD_DASHBOARD', label: 'Dashboard' },
    { id: 'PROD_DAILY', label: 'Daily Production' },
    { id: 'PROD_MACHINES', label: 'Machine Monitoring' },
    { id: 'PROD_DOWNTIME', label: 'Down-Time Entry' },
    { id: 'PROD_REPORTS', label: 'Reports' },
  ],
  PLANNING: [
    { id: 'MOD_PLANNING', label: 'Access PLANNING Module' },
    { id: 'PLAN_DASHBOARD', label: 'Dashboard' },
    { id: 'PLAN_SCHEDULE', label: 'Prod Scheduling' },
    { id: 'PLAN_MRP', label: 'MRP Run' },
    { id: 'PLAN_CAPACITY', label: 'Capacity Planning' },
    { id: 'PLAN_REPORTS', label: 'Reports' },
  ],
  ENGINEERING: [
    { id: 'MOD_ENGINEERING', label: 'Access ENGINEERING Module' },
    { id: 'ENG_DASHBOARD', label: 'Dashboard' },
    { id: 'ENG_ITEMS', label: 'Item Master' },
    { id: 'ENG_BOM', label: 'Bill of Materials' },
    { id: 'ENG_BOM_DIFF', label: 'BOM Comparison' },
    { id: 'ENG_ROUTING', label: 'Routing Master' },
    { id: 'ENG_WORK_CENTERS', label: 'Work Center Master' },
    { id: 'ENG_REPORTS', label: 'Reports' },
  ],
  MARKETING: [
    { id: 'MOD_MARKETING', label: 'Access MARKETING Module' },
    { id: 'MARK_DASHBOARD', label: 'Dashboard' },
    { id: 'MARK_LEADS', label: 'Leads / Enquiries' },
    { id: 'MARK_QUOTES', label: 'Quotations' },
    { id: 'MARK_ORDERS', label: 'Sales Orders' },
    { id: 'MARK_CUSTOMERS', label: 'Customer Master' },
    { id: 'MARK_REPORTS', label: 'Reports' },
  ],
  QUALITY: [
    { id: 'MOD_QUALITY', label: 'Access QUALITY Module' },
    { id: 'QUAL_DASHBOARD', label: 'Dashboard' },
    { id: 'QUAL_INCOMING', label: 'Incoming Inspection' },
    { id: 'QUAL_PROCESS', label: 'In-Process Inspection' },
    { id: 'QUAL_FINAL', label: 'Final QC / PDI' },
    { id: 'QUAL_REPORTS', label: 'Reports' },
  ],
  MAINTENANCE: [
    { id: 'MOD_MAINTENANCE', label: 'Access MAINTENANCE Module' },
    { id: 'MAINT_DASHBOARD', label: 'Dashboard' },
    { id: 'MAINT_MACHINES', label: 'Machine Master' },
    { id: 'MAINT_ASSETS', label: 'Asset Register' },
    { id: 'MAINT_SCHEDULE', label: 'PM Schedule' },
    { id: 'MAINT_REPORTS', label: 'Reports' },
  ],
  SUBCONTRACT: [
    { id: 'MOD_SUBCONTRACT', label: 'Access SUBCONTRACT Module' },
    { id: 'SUB_DASHBOARD', label: 'Dashboard' },
    { id: 'SUB_ORDERS', label: 'Job Work Orders' },
    { id: 'SUB_ISSUE', label: 'Material Issue' },
    { id: 'SUB_RECEIPT', label: 'Material Receipt' },
    { id: 'SUB_REPORTS', label: 'Reports' },
  ]
};
