CREATE USER AUCTOR IDENTIFIED BY auctor_pass DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO AUCTOR;
GRANT IMP_FULL_DATABASE TO AUCTOR;
CREATE OR REPLACE DIRECTORY DMPDIR AS '/opt/oracle';
GRANT READ, WRITE ON DIRECTORY DMPDIR TO AUCTOR;
GRANT READ, WRITE ON DIRECTORY DMPDIR TO SYSTEM;
EXIT
