BEGIN;
UPDATE m_item_master SET item_name='NORMAL TOP (FRONT) WHITE', make_buy='Make', is_stock_item=true, is_purchase_item=false WHERE item_code='TFAN0001';
UPDATE m_item_master SET item_name='BOTTOM (BACK) WHITE', make_buy='Make', is_stock_item=true, is_purchase_item=false WHERE item_code='TFAN0002';
UPDATE m_item_master SET item_name='NORMAL SWING PLATE (SLIDER)', make_buy='Buy' WHERE item_code='TFAN0003';
UPDATE m_item_master SET item_name='STOPPER PLATE', make_buy='Buy' WHERE item_code='TFAN0004';
UPDATE m_item_master SET item_name='LOWERS 2PCS', make_buy='Buy' WHERE item_code='TFAN0005';
UPDATE m_item_master SET item_name='D PLATE', make_buy='Buy' WHERE item_code='TFAN0006';
UPDATE m_item_master SET item_name='CAP SET BOTTOM', make_buy='Buy' WHERE item_code='TFAN0007';
UPDATE m_item_master SET item_name='CAP SET TOP', make_buy='Buy' WHERE item_code='TFAN0008';
UPDATE m_item_master SET item_name='DERLIN ROUND PART', make_buy='Buy' WHERE item_code='TFAN0009';
UPDATE m_item_master SET item_name='NANDUS DIPPED IN OIL', make_buy='Buy' WHERE item_code='TFAN0010';
UPDATE m_item_master SET item_name='SPRING', make_buy='Buy' WHERE item_code='TFAN0011';
UPDATE m_item_master SET item_name='MOTOR BASE BLACK', make_buy='Make' WHERE item_code='TFAN0012';
UPDATE m_item_master SET item_name='BLOWER TOP PLATE', make_buy='Buy' WHERE item_code='TFAN0013';
UPDATE m_item_master SET item_name='PIN INSERT FOR BLOWER TOP PLATE', make_buy='Buy' WHERE item_code='TFAN0014';
UPDATE m_item_master SET item_name='BLOWER BOTTOM PLATE', make_buy='Buy' WHERE item_code='TFAN0015';
UPDATE m_item_master SET item_name='BLOWER BUSH RUBBER', make_buy='Buy' WHERE item_code='TFAN0016';
UPDATE m_item_master SET item_name='BLOWER SECTIONS', make_buy='Buy' WHERE item_code='TFAN0017';
UPDATE m_item_master SET item_name='BLOWER BALANCING PINS', make_buy='Buy' WHERE item_code='TFAN0018';
UPDATE m_item_master SET item_name='NORMAL KNOBS WHITE', make_buy='Buy' WHERE item_code='TFAN0019';
UPDATE m_item_master SET item_name='NORMAL ON OFF PLATE', make_buy='Buy' WHERE item_code='TFAN0020';
UPDATE m_item_master SET item_name='RUBBER ITEMS BOTTOM BUSH 4+GROMET1', make_buy='Buy' WHERE item_code='TFAN0021';
UPDATE m_item_master SET item_name='PACKING COVERS', make_buy='Buy' WHERE item_code='TFAN0022';
UPDATE m_item_master SET item_name='MOTOR WITH 4MFD CAPACITOR', make_buy='Buy' WHERE item_code='TFAN0023';
UPDATE m_item_master SET item_name='SWING MOTOR WITH BUSH', make_buy='Buy' WHERE item_code='TFAN0024';
UPDATE m_item_master SET item_name='ON/OFF SWITCH ELCOM', make_buy='Buy' WHERE item_code='TFAN0025';
UPDATE m_item_master SET item_name='3 SPEED SWITCH ELCOM', make_buy='Buy' WHERE item_code='TFAN0026';
UPDATE m_item_master SET item_name='POWER CORD 2.5M 2CORE', make_buy='Buy' WHERE item_code='TFAN0027';
UPDATE m_item_master SET item_name='HARDWARE PACKING SET', make_buy='Buy' WHERE item_code='TFAN0028';
UPDATE m_item_master SET item_name='INNER CARTON', make_buy='Buy' WHERE item_code='TFAN0029';
UPDATE m_item_master SET item_name='OUTER CARTON', make_buy='Buy' WHERE item_code='TFAN0030';
UPDATE m_item_master SET item_name='MANUAL & WARRANTY CARD', make_buy='Buy' WHERE item_code='TFAN0031';
UPDATE m_item_master SET item_name='MRP AND OTHER LABELS', make_buy='Buy' WHERE item_code='TFAN0032';
UPDATE m_item_master SET item_name='DOOM TOP (FRONT) WHITE', make_buy='Make' WHERE item_code='TFAN0033';
UPDATE m_item_master SET item_name='DOOM KNOBS WHITE', make_buy='Buy' WHERE item_code='TFAN0034';
UPDATE m_item_master SET item_name='DOOM ON OFF PLATE', make_buy='Buy' WHERE item_code='TFAN0035';
UPDATE m_item_master SET item_name='HIGH BREEZE TOP (FRONT) WHITE', make_buy='Make' WHERE item_code='TFAN0036';
UPDATE m_item_master SET item_name='HIGH BREEZE SWING PLATE (SLIDER)', make_buy='Buy' WHERE item_code='TFAN0037';
UPDATE m_item_master SET item_name='HIGH BREEZE LOWERS STICK', make_buy='Buy' WHERE item_code='TFAN0038';
UPDATE m_item_master SET item_name='HIGH BREEZE LOWERS UP DOWN', make_buy='Buy' WHERE item_code='TFAN0039';
UPDATE m_item_master SET item_name='HIGH BREEZE LOWERS CONTROLLER SET', make_buy='Buy' WHERE item_code='TFAN0040';
UPDATE m_item_master SET item_name='HIGH BREEZE LOWERS 5PCS', make_buy='Buy' WHERE item_code='TFAN0041';
UPDATE m_item_master SET item_name='HIGH BREEZE KNOBS WHITE', make_buy='Buy' WHERE item_code='TFAN0042';
UPDATE m_item_master SET item_name='HIGH BREEZE ON OFF PLATE', make_buy='Buy' WHERE item_code='TFAN0043';
UPDATE m_item_master SET item_name='PERFUME TOP (FRONT) WHITE', make_buy='Make' WHERE item_code='TFAN0044';
UPDATE m_item_master SET item_name='COLORED FRONT PANEL', make_buy='Buy' WHERE item_code='TFAN0045';
UPDATE m_item_master SET item_name='PERFUME SWING PLATE (SLIDER)', make_buy='Buy' WHERE item_code='TFAN0046';
UPDATE m_item_master SET item_name='PERFUME KNOBS WHITE', make_buy='Buy' WHERE item_code='TFAN0047';
UPDATE m_item_master SET item_name='PERFUME ON OFF PLATE', make_buy='Buy' WHERE item_code='TFAN0048';
UPDATE m_item_master SET is_active=true WHERE item_code LIKE 'TFAN00%' AND item_code <= 'TFAN0048';
UPDATE m_item_master SET is_active=false WHERE item_code IN ('COMP0001','HARD0001','HARD0002','HARD0003','HARD0004','HARD0005');
COMMIT;
