import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { useCompany } from '../../context/CompanyContext';

const PAGE_TITLES = [
  ['/accounts/coa', 'Chart of Accounts'],
  ['/accounts/budgets', 'Budgets'],
  ['/accounts/settings', 'Account Settings'],
  ['/invoice/sales', 'Sales Invoices'],
  ['/invoice/purchase', 'Purchase Invoices'],
  ['/invoice/debit-note', 'Debit Notes'],
  ['/invoice/credit-note', 'Credit Notes'],
  ['/accounts/payment', 'Payment Vouchers'],
  ['/accounts/receipt', 'Receipt Vouchers'],
  ['/accounts/journal', 'Journal Vouchers'],
  ['/accounts/contra', 'Contra Vouchers'],
  ['/accounts/voucher', 'Vouchers'],
  ['/accounts', 'Accounts Dashboard'],
  ['/reports/ledger', 'Ledger Report'],
  ['/reports/daybook', 'Day Book'],
  ['/reports/trial-balance', 'Trial Balance'],
  ['/reports/pl', 'Profit & Loss'],
  ['/reports/balance-sheet', 'Balance Sheet'],
  ['/reports/ap', 'Accounts Payable'],
  ['/reports/ar', 'Accounts Receivable'],
  ['/purchase/requisitions', 'Purchase Requisitions'],
  ['/purchase/orders', 'Purchase Orders'],
  ['/purchase/rfq', 'RFQ'],
  ['/purchase/prices', 'Price List'],
  ['/purchase/rating', 'Vendor Rating'],
  ['/purchase/vendors', 'Vendor Master'],
  ['/purchase/approvals', 'Purchase Approvals'],
  ['/purchase/job-orders', 'Job Orders'],
  ['/purchase/pr-amendment', 'PR Amendment'],
  ['/purchase/settings', 'Purchase Settings'],
  ['/purchase/daily-reports', 'Daily Reports'],
  ['/purchase/reports', 'Purchase Reports'],
  ['/purchase', 'Purchase Dashboard'],
  ['/stores/approvals', 'Stores Approvals'],
  ['/stores/item-master', 'Item Master'],
  ['/stores/uom', 'UOM Master'],
  ['/stores/item-groups', 'Item Group Master'],
  ['/stores/item-types', 'Item Type Master'],
  ['/stores/grr-billing', 'GRR Billing'],
  ['/stores/grr', 'Goods Receipt'],
  ['/stores/material-requisitions', 'Material Requisitions'],
  ['/stores/material-issues', 'Material Issues'],
  ['/inventory/ledger', 'Stock Ledger'],
  ['/stores/day-wise-stock', 'Day Wise Stock'],
  ['/stores/stock-audit', 'Stock Audit'],
  ['/stores/gate-entry', 'Gate Entry'],
  ['/stores/material-returns', 'Material Returns'],
  ['/stores/delivery-challans/repair', 'Repair Challan'],
  ['/stores/delivery-challans/maintenance', 'Maintenance Challan'],
['/stores/delivery-challans', 'Delivery Challan'],
['/stores/inward-registers', 'Inward Register'],
['/stores/sale-approval', 'Sale on Approval'],
  ['/stores/invoices', 'Tax Invoices'],
  ['/stores/settings', 'Stores Settings'],
  ['/stores/reports', 'Stores Reports'],
  ['/stores', 'Stores Dashboard'],
  ['/production/orders', 'Production Orders'],
  ['/production/machines', 'Machines'],
  ['/production/daily-entry', 'Daily Entry'],
  ['/production/downtime', 'Downtime'],
  ['/production/settings', 'Production Settings'],
  ['/production/reports', 'Production Reports'],
  ['/production', 'Production Dashboard'],
  ['/planning/schedule', 'Production Schedule'],
  ['/planning/mrp', 'Material Requirements Planning'],
  ['/planning/capacity', 'Capacity Planning'],
  ['/planning/settings', 'Planning Settings'],
  ['/planning/reports', 'Planning Reports'],
  ['/planning', 'Planning Dashboard'],
  ['/engineering/categories', 'Category Master'],
  ['/engineering/products', 'Product Master'],
  ['/engineering/bom', 'Bill of Materials'],
  ['/engineering/settings', 'Engineering Settings'],
  ['/engineering/reports', 'Engineering Reports'],
  ['/engineering', 'Engineering Dashboard'],
  ['/quality/inspections', 'Inspections'],
  ['/quality/non-conformances', 'Non-Conformances'],
  ['/quality/incoming', 'Incoming Inspections'],
  ['/quality/process', 'Process Inspections'],
  ['/quality/final', 'Final Inspections'],
  ['/quality/settings', 'Quality Settings'],
  ['/quality/reports', 'Quality Reports'],
  ['/quality', 'Quality Dashboard'],
  ['/marketing/customers', 'Customer Master'],
  ['/marketing/leads', 'Leads'],
  ['/marketing/quotes', 'Quotations'],
  ['/marketing/orders', 'Sales Orders'],
  ['/marketing/settings', 'Marketing Settings'],
  ['/marketing/reports', 'Marketing Reports'],
  ['/marketing', 'Marketing Dashboard'],
  ['/subcontract/orders', 'Subcontract Orders'],
  ['/subcontract/issue', 'Subcontract Issues'],
  ['/subcontract/receipt', 'Subcontract Receipts'],
  ['/subcontract/settings', 'Subcontract Settings'],
  ['/subcontract/reports', 'Subcontract Reports'],
  ['/subcontract', 'Subcontract Dashboard'],
  ['/maintenance/machines', 'Maintenance Machines'],
  ['/maintenance/assets', 'Assets'],
  ['/maintenance/schedule', 'Maintenance Schedule'],
  ['/maintenance/settings', 'Maintenance Settings'],
  ['/maintenance/reports', 'Maintenance Reports'],
  ['/maintenance', 'Maintenance Dashboard'],
  ['/employee-report', 'Employee Report'],
  ['/add-employee', 'Add Employee'],
  ['/edit-employee', 'Edit Employee'],
  ['/employees', 'Employees'],
  ['/profile-requests', 'Profile Requests'],
  ['/leave-report', 'Leave Report'],
  ['/leaves-master', 'Leave Master'],
  ['/leave', 'Leave Applications'],
  ['/onduty-preview', 'On-Duty Preview'],
  ['/onduty', 'On-Duty'],
  ['/shiftchange', 'Shift Change'],
  ['/attendance-mod', 'Attendance Modification'],
  ['/hr-attendance', 'HR Attendance'],
  ['/tour', 'Tour'],
  ['/woffchange', 'Weekly Off Change'],
  ['/advance', 'Advance'],
  ['/esileave', 'ESI Leave'],
  ['/tax', 'Employee Tax'],
  ['/recruitment', 'Recruitment'],
  ['/exit-settlement', 'Exit Settlement'],
  ['/training', 'Training'],
  ['/pms', 'Performance Management'],
  ['/disciplinary', 'Disciplinary'],
  ['/attendance-collector', 'Attendance Collector'],
  ['/pf-accounting', 'PF Accounting'],
  ['/payroll', 'Payroll'],
  ['/holidays', 'Holiday Master'],
  ['/shift-master', 'Shift Master'],
  ['/shiftschedule', 'Shift Schedule'],
  ['/muster-roll', 'Muster Roll'],
  ['/ot-approval', 'OT Approval'],
  ['/photo', 'Photo Upload'],
  ['/useraccess', 'User Access'],
  ['/profile', 'My Profile'],
  ['/change-password', 'Change Password'],
  ['/hr/settings', 'Settings'],
  ['/settings', 'Settings'],
  ['/reports', 'Reports'],
  ['/hr', 'HR Dashboard'],
];

const getPageTitle = (pathname) => {
  const match = PAGE_TITLES.find(([prefix]) => pathname.startsWith(prefix));
  return match ? match[1] : null;
};

const getShortName = (companyName) => {
  const name = (companyName || '').trim();
  return name.split(/\s+/)[0] || 'AUCTOR';
};

const DocumentTitle = () => {
  const { pathname } = useLocation();
  const { companyName } = useCompany();

  useEffect(() => {
    const pageTitle = getPageTitle(pathname);
    if (pageTitle) {
      document.title = `${getShortName(companyName)} : ${pageTitle}`;
    }
  }, [pathname, companyName]);

  return null;
};

export default DocumentTitle;
